name: Deploy Copilot Metrics Viewer to AWS

on:
  push:
    branches:
      - pg

permissions:
  contents: read


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          ECR_REPO: ${{vars.ECR_REPO}}
        run: >-
          docker build --no-cache --progress=plain --rm
          -t $ECR_PREFIX/$ECR_REPO/app:latest
          -f api.Dockerfile .

  Push:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Login AWS ECR
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          AWS_REGION: ${{vars.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: >-
          aws ecr get-login-password --region $AWS_REGION 
          | docker login --username AWS --password-stdin $ECR_PREFIX

      - name: Push Docker Image
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          ECR_REPO: ${{vars.ECR_REPO}}
        run: >-
          docker push $ECR_PREFIX/$ECR_REPO/app:latest
