name: Deploy Copilot Metrics Viewer to AWS

on:
  push:
    branches:
      - main

permissions:
  contents: read


jobs:
  Delpoy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Build
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          ECR_REPO: ${{vars.ECR_REPO}}
        run: >-
          docker build --no-cache --progress=plain --rm
          -t $ECR_PREFIX/$ECR_REPO:latest
          -f api.Dockerfile --platform linux/amd64 .

      - name: Login AWS ECR
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          AWS_REGION: ${{vars.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: >-
          aws ecr get-login-password --region $AWS_REGION 
          | docker login --username AWS --password-stdin $ECR_PREFIX

      - name: Push Docker Image
        env:
          ECR_PREFIX: ${{vars.ECR_PREFIX}}
          ECR_REPO: ${{vars.ECR_REPO}}
        run: >-
          docker push $ECR_PREFIX/$ECR_REPO:latest

      - name: CDK Deploy
        env:
          VUE_APP_GITHUB_TOKEN: ${{secrets.VUE_APP_GITHUB_TOKEN}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          AWS_REGION: ${{vars.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          cd ./cdk
          npm install
          npm run deploy
